name: Auto merge to develop branch

on:
  pull_request:
    branches: main
    types: [closed]

jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        run: |
          echo "cd .github/src"
          cd .github/src
          echo "npm install"
          npm install
          echo "create_staging_release_pr.js start"
          node create_staging_release_pr.js
        env:
          HEAD_BRANCH: ${{ github.head_ref }}
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          TEMPLATE: ${{ github.workspace }}/.github/git-pr-release.template

