name: Auto merge to develop

on:
  pull_request:
    branches: main
    types: [closed]

jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        run: |
          echo "The branch name is $GITHUB_BASE_REF"
          git checkout develop
          git merge $GITHUB_BASE_REF --no-ff --no-edit
          git push origin develop
          
